### ISSUE TITLE
DailyCard-18-09

### ISSUE THREAD

**Issue by FrizzleFur** [FrizzleFur/DailyLearning#8]
### 今天规划

* 今天主要以学习为主
* 下午晚点去跑步

### 学习收获（源码、书籍、文章）

* [SwipeTableView](https://github.com/Roylee-ML/SwipeTableView) 看了架构，类似捕手发现的模块,tabBar下面对应一个滚动的多个竖直方向的视图，
* [NJHu/iOSProject](https://github.com/NJHu/iOSProject) 虽然也是iOS的Demo集合，但是看README后感觉很想学，整理的比较好吧。作者对`issue`的回复也很有范：
![](http://oc98nass3.bkt.clouddn.com/15210858045247.jpg)
* [NJHu/vue](https://github.com/NJHu/vue) 是一个很好学习前端`JavaScript`的好资源

### 回顾感想

* [SwipeTableView](https://github.com/Roylee-ML/SwipeTableView)作者做`iOS`只有一年时间，对比自己，倍感惭愧。学习需要提高效率和专注，戒骄戒躁。沉下❤️来才能快速前行。
* 记录很重要，但是回顾才能有所收获
* 就想房间需要定期清理一样，生活和学习都需要定期的`Review`, 清除垃圾，提高效率。
* [ShannonChenCHN的周报记录](https://github.com/ShannonChenCHN/iOSLevelingUp/issues/102#issuecomment-370279100)给我很大的启发，自己一直在零散的记录，没有形成知识体系是很伤的，反应出不够专注吧。

**Comment by FrizzleFur** [comment]
### 2018-03-16

### 今天规划

* 整理了日记
* 删除了备份硬盘的过期备份

### 学习收获（源码、书籍、文章）

整理了一些资料吧

**Comment by FrizzleFur** [comment]
### 2018-03-17

### 今天规划

- [ ] 将`CmdMarkdown` 和马克飞象的日记整理到`DayOne`
- [ ] 整理印象笔记
- [ ] 整理百度云盘资料
- [ ] 整理`RSS`资料
- [ ] 整理`Onenote`资料

### 学习收获（源码、书籍、文章）



#### 自动化CI集成

1. Fastlane的学习
2. 单元测试的编写
3. 对Xcode的Bot的使用，代码覆盖率的检查。

**Comment by FrizzleFur** [comment]
### 2018-03-18

### 今天规划

### 学习收获（源码、书籍、文章）

需要阅读的

- [ ] 整理印象笔记
- [ ] 整理百度云盘资料
- [ ] 整理`RSS`资料
- [ ] 整理`Onenote`资料

**Comment by FrizzleFur** [comment]
### 2018-03-28

### 今天规划

### 学习收获（源码、书籍、文章）

TODO
- [ ] iOS几个重点难点
    - [ ] iOS的block知识
    - [ ] iOS的多线程
    - [ ] iOS中如何发请求
 * 捕手项目的进一步梳理
* 深入学习Swift

**Comment by FrizzleFur** [comment]
### 2018-03-30

### 今天规划

### 学习收获（源码、书籍、文章）

#### TODO
- [ ] iOS的block知识
- [ ] 下载《程序是如何跑起来的》
- [ ] 阅读《计算机组成原理》

**Comment by FrizzleFur** [comment]
### 2018-04-01

- [ ] 完成阅读《程序是如何跑起来的》

**Comment by FrizzleFur** [comment]
- [x] 完成阅读《网络是怎样连接的》
     - [x] 完成第5章
     - [x] 完成第6章
     - [x] 完成第7章
     - [x] 完成第8章
     - [x] 完成第9章
     - [x] 完成第10章
     - [x] 完成第11章
     - [x] 完成第12章

**Comment by FrizzleFur** [comment]
### 2018-04-07

### 今天规划

- [ ] 完成阅读《网络是怎样连接的》
     - [ ] 完成第1章
     - [ ] 完成第2章
     - [ ] 完成第3章
     - [ ] 完成第4章
     - [ ] 完成第5章
     - [ ] 完成第6章

- [x ] 晚上跑步
- [ ] 复习Block 
- [ ] 查看《图解TCP/IP》

**Comment by FrizzleFur** [comment]
### 2018-04-14

### 今天规划

- [ ] [HTML 教程- (HTML5 标准)](http://www.runoob.com/html/html-tutorial.html)

- [ ] 完成阅读《网络是怎样连接的》
     - [ ] 完成第1章
     - [ ] 完成第2章
     - [ ] 完成第3章
     - [ ] 完成第4章
     - [ ] 完成第5章
     - [ ] 完成第6章

#### TODO
- [ ] iOS几个重点难点
    - [ ] iOS的block知识
    - [ ] iOS的多线程
    - [ ] iOS中如何发请求
* **将Demo上传到`DailyLearning/iOSLearningDemo/`中**
* 捕手项目的进一步梳理
* 深入学习Swift
- [ ] 查看《图解TCP/IP》
- [ ] 复习Block 

### Git
[Git 从入门到放弃](http://m.quzhiboapp.com/#!/intro/68)

**Comment by FrizzleFur** [comment]
### 2018-04-15

### 今天规划

* 每天一件推动核心目标的重要任务。
* 每天三件日程上必须要完成的任务。
* 每天五件工作生活中被交代处理的琐事。

### Snoozed

- [ ] 完成阅读《网络是怎样连接的》✨
     - [ ] 完成第1章
     - [ ] 完成第2章
     - [ ] 完成第3章
     - [ ] 完成第4章
     - [ ] 完成第5章
     - [ ] 完成第6章


#### 任务备忘

- [ ] iOS几个重点难点
    - [ ] iOS的block知识
    - [ ] iOS的多线程
    - [ ] iOS中如何发请求
* **将Demo上传到`DailyLearning/iOSLearningDemo/`中**
* 捕手项目的进一步梳理
* 深入学习Swift
- [ ] 查看《图解TCP/IP》
- [ ] 复习Block 

### Git
[Git 从入门到放弃](http://m.quzhiboapp.com/#!/intro/68)


[iOS源码补完计划--SDWebImage4.0+源码参阅(附面试题/流程图) - 简书](https://www.jianshu.com/p/3b8a7ae966d3)

[iOS源码补完计划--AFNetworking 3.1.0源码研读 - 简书](https://www.jianshu.com/p/d085525cc88b)

[iOS基础深入补完计划--Block相关原理探究 - 简书](https://www.jianshu.com/p/083315ba7671)

**Comment by FrizzleFur** [comment]
### 2018-04-28

### 今天规划

* 每天一件推动核心目标的重要任务。
* 每天三件日程上必须要完成的任务。
* 每天五件工作生活中被交代处理的琐事。


- [ ] XMPP 教程，复习项目的环信
- [ ] Git 教程完善

### Snoozed
- [ ] Reeder 教程
- [ ] Trailer 教程
- [ ] 完成阅读《网络是怎样连接的》✨
     - [ ] 完成第1章
     - [ ] 完成第2章
     - [ ] 完成第3章
     - [ ] 完成第4章
     - [ ] 完成第5章
     - [ ] 完成第6章


#### 任务备忘

- [ ] [技术博客](https://huangxuan.me/2017/07/12/upgrading-eleme-to-pwa/)
- [ ] 吕立青的博客做出文档
 
- [ ] iOS几个重点难点
    - [ ] iOS的block知识
    - [ ] iOS的多线程
    - [ ] iOS中如何发请求
* **将Demo上传到`DailyLearning/iOSLearningDemo/`中**
* 捕手项目的进一步梳理
* 深入学习Swift
- [ ] 查看《图解TCP/IP》
- [ ] 复习Block 

### Git
[Git 从入门到放弃](http://m.quzhiboapp.com/#!/intro/68)



[iOS源码补完计划--SDWebImage4.0+源码参阅(附面试题/流程图) - 简书](https://www.jianshu.com/p/3b8a7ae966d3)

[iOS源码补完计划--AFNetworking 3.1.0源码研读 - 简书](https://www.jianshu.com/p/d085525cc88b)

[iOS基础深入补完计划--Block相关原理探究 - 简书](https://www.jianshu.com/p/083315ba7671)

**Comment by FrizzleFur** [comment]
### 2018-08-10

### 今天规划

* 每天一件推动核心目标的重要任务。
* 每天三件日程上必须要完成的任务。
* 每天五件工作生活中被交代处理的琐事。


- [ ] 整理Github的知识wiki✨

- [ ] 查看懒人demo✨

- [ ] 完成阅读《网络是怎样连接的》✨
     - [ ] 完成第1章
     - [ ] 完成第2章
     - [ ] 完成第3章
     - [ ] 完成第4章
     - [ ] 完成第5章
     - [ ] 完成第6章

**Comment by FrizzleFur** [comment]
### 2018-09-11

### 今天规划

* 每天一件推动核心目标的重要任务。
* 每天三件日程上必须要完成的任务。
* 每天五件工作生活中被交代处理的琐事。

* [ ] 首页
    * [ ] MJRefresh刷新
    * [ ] 网络异常界面
    * [ ] 自定义Cell
    * [ ] 首页悬浮
* [ ] 详情页
    * [ ] cell图片
    * [ ] 评论
* [ ] 明星主页
    * [ ] 明星展示首页
    * [ ] 明星推荐关注页

**Comment by FrizzleFur** [comment]
## 2018-09-12

* [ ] 首页
    * [ ] 首页banner，page的点的显示问题
    * [ ] 下拉刷新gif

**Comment by FrizzleFur** [comment]
## 2018-09-14

## 首页

 - [ ] 完善接口
 - [ ] 完善卡片cell

### Snoozed
* [ ] 详情页
    * [ ] cell图片
    * [ ] 评论

* [ ] 网络异常界面

* [ ] 明星主页
    * [ ] 明星展示首页
    * [ ] 明星推荐关注页

**Comment by FrizzleFur** [comment]
## 2018-09-14


* [ ] 详情页
    * [ ] cell图片
    * [ ] 评论

### Snoozed
* [ ] 网络异常界面

* [ ] 明星主页
    * [ ] 明星展示首页
    * [ ] 明星推荐关注页

**Comment by FrizzleFur** [comment]
* [ ] 咨询详情页
    * [x] 咨询详情页接口，和数据的处理
    * [x] cell图片
    * [ ] 底部bar的封装
    * [ ] 点击图片预览
    * [ ] 视频页播放

### Snoozed

* [ ] 明星主页
    * [ ] 明星展示首页
    * [ ] 明星关注添加
    * [ ] 明星动态页面
    * [ ] 明星相册页


* [ ] 咨询详情页评论

* [ ] 网络异常界面

**Comment by FrizzleFur** [comment]
## 2018-09-18

* [ ] 网络异常界面

* [ ] 咨询详情页
    * [ ] 点击图片预览
    * [ ] 视频页播放

### Snoozed

* [ ] 明星主页
    * [ ] 明星展示首页
    * [ ] 明星关注添加
    * [ ] 明星动态页面
    * [ ] 明星相册页

* [ ] 咨询详情页评论

**Comment by FrizzleFur** [comment]
##2018-09-19

* [ ] 咨询详情页
    * [ ] 点击图片预览
    * [ ] 视频页播放

* [ ] 明星主页
    * [ ] 明星展示首页
    * [ ] 明星关注添加页的排布
    * [ ] 明星动态页面
    * [ ] 明星相册页

### Snoozed
* [ ] 网络异常界面

* [ ] 咨询详情页评论

**Comment by FrizzleFur** [comment]
##2018-09-20

* [ ] 咨询详情页
    * [ ] 点击图片预览
    * [ ] 视频页播放

### Snoozed
    * [ ] 明星展示首页
    * [ ] 明星动态页面
    * [ ] 明星相册页


* [ ] 网络异常界面
* [ ] 反黑标记助手
* [ ] 反黑净化广场
* [ ] 网络异常界面

**Comment by FrizzleFur** [comment]
##2018-09-21

* [ ] 明星展示首页
* [ ] 明星动态页面

* [ ] 反黑标记助手
* [ ] 反黑净化广场

### Snoozed


* [ ] 咨询详情页
    * [x] 点击图片预览
    * [ ] 视频页播放

* [ ] 网络异常界面
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-22

* [ ] 明星展示首页咨询接口

* [ ] 反黑标记助手
* [ ] 反黑净化广场

### Snoozed


* [ ] 咨询详情页
    * [x] 点击图片预览
    * [ ] 视频页播放

* [ ] 网络异常界面
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-23

* [ ] 咨询详情页
    * [ ] 点击图片预览
    * [ ] 视频页播放

### Snoozed
* [ ] 明星展示首页咨询接口

* [ ] 反黑标记助手
* [ ] 反黑净化广场

* [ ] 网络异常界面
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-25


* [x] 关注列表变化时和tabbar以及首页我的关注数据同步
* [x] 登录后的tabbar以及首页我的关注数据同步

* [ ] 点击图片预览无响应
* [ ] 反黑标记助手

### Snoozed
* [ ] 明星展示首页咨询接口
* [ ] 反黑净化广场API
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-27

* [ ] 反黑标记助手API
* [ ] 反黑标记助手UI

### Snoozed
* [ ] 首页下拉刷新问题
* [ ] 关注列表的数据同步问题
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-28

* [ ] 明星tabbar的头像显示，看能否加动画
* [ ] 明星tabbar的头像引导

### Snoozed
* [ ] 反黑标记助手空页面
* [ ] 首页下拉刷新问题
* [ ] 明星主页的banner的pageControl大小问题
* [ ] 关注列表的数据同步问题
* [ ] 行程加入日历
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-29

* [ ] 一键打榜demo
* [ ] 首页下拉刷新问题
* [ ] 反黑标记助手空页面

### Snoozed

* [ ] 明星tabbar的头像显示，看能否加动画
* [ ] 明星tabbar的头像引导

* [ ] 关注列表的数据同步问题
* [ ] 行程加入日历
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-30

* [ ] 一键打榜demo
* [ ] 首页下拉刷新问题
* [ ] 反黑标记已标记

* [ ] 明星tabbar的头像引导
* [ ] 明星tabbar的头像显示，看能否加动画

* [ ] 行程加入日历
* [ ] 分享
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-09-30
## 2018-10-01
* [ ] SDWebimage下载处理
* [ ] 一键打榜demo
* [ ] 首页下拉刷新问题

## SNOOZED
* [ ] 行程加入日历
* [ ] 分享
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-10-02

* [ ] 一键打榜demo
* [ ] 首页下拉刷新问题
* [ ] 关注列表同步

## SNOOZED
* [ ] 行程加入日历
* [ ] 分享
* [ ] 明星相册页

**Comment by FrizzleFur** [comment]
## 2018-10-03

* [ ] 一键打榜demoUI
* [ ] 首页下拉刷新问题

## SNOOZED
* [ ] 关注列表同步

* [ ] 行程加入日历
* [ ] 分享
* [ ] 明星相册页
* [ ] code review
* [ ] CI 集成

**Comment by FrizzleFur** [comment]
## 2018-10-03


* [ ] 一键打榜demoUI
* [ ] 首页下拉刷新问题
## SNOOZED
* [ ] 行程加入日历
* [ ] 分享
* [ ] code review
* [ ] CI 集成

**Comment by FrizzleFur** [comment]
## 2018-10-04
* [ ]  一键打榜功能
* [ ]  明星主页修改
* [ ]  新手引导页
* [ ]  需求细节对应

## SNOOZED
* [ ] 行程加入日历
* [ ] 分享
* [ ] code review
* [ ] CI 集成

**Comment by FrizzleFur** [comment]
## 2018-10-09

* [ ]  行程banner空样式
* [ ]  一键打榜功能
* [ ]  下拉刷新的bug---参考微博的刷新，直接加载3个Table

## SNOOZED

* [ ]  明星主页修改
* [ ]  新手引导页
* [ ] 分享接口
* [ ] code review
* [ ] Jenkins 集成

**Comment by FrizzleFur** [comment]
## 2018-10-10

* [ ]  下拉刷新的bug---参考微博的刷新，直接加载3个Table

## SNOOZED

* [ ]  新手引导页
* [ ] 分享接口
* [ ] code review
* [ ] Jenkins 集成

**Comment by FrizzleFur** [comment]
## 2018-10-11

* [ ]  下拉刷新的bug---参考微博的刷新，直接加载3个Table
* [ ]  新手引导页

## SNOOZED

* [ ] 分享接口
* [ ] code review
* [ ] Jenkins 集成

**Comment by FrizzleFur** [comment]
## 2018-10-12


* [ ]  下拉刷新的bug---参考微博的刷新，直接加载3个Table

## SNOOZED

* [ ] code review
* [ ] Jenkins 集成

**Comment by FrizzleFur** [comment]
## 2018-10-13

* [ ]  微博转发富文本，和连接的跳转
* [ ] 明星页面
* [ ] 明星二级页
* [ ] 任务+领取

## SNOOZED

* [ ] code review

**Comment by FrizzleFur** [comment]
## 2018-10-14

* [ ]  微博转发富文本，和连接的跳转
* [ ] 明星页面

## SNOOZED
* [ ] 明星二级页
* [ ] 任务+领取
* [ ] code review

**Comment by FrizzleFur** [comment]
## 2018-10-15

* [ ] 明星页面初步搭建和接口调整
* [ ] 打榜UI调整和接口完善
* [ ] 悬浮页架构

## SNOOZED

* [ ] 明星页面动画调整
* [ ] 明星二级页
* [ ]  微博转发富文本，和连接的跳转，
* [ ]  多图的视频点击

* [ ] 任务+领取
* [ ] code review
